sudo: required
language: python
python:
- '2.7'
addons:
  apt:
    packages:
    - docker-ce
branches:
  only:
  - master
install:
- git remote -v
script:
- bash main.sh
before_install:
- export start_time=$(date +%s)
- mkdir -p ~/.docker
- mkdir -p ~/.ssh
- openssl aes-256-cbc -K $encrypted_f77e1c3ec90c_key -iv $encrypted_f77e1c3ec90c_iv
  -in ./travis/config.tar.gz.enc -out config.tar.gz -d
- tar zxf ~/config.tar.gz -C ~
- mv ~/config.json ~/.docker/
- mv ~/id_rsa ~/.ssh/
- chmod 600 ~/.ssh/id_rsa
- chmod 600 ~/.docker/config.json
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- df -h
